
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vinod Tahelyani
 */
public class front extends javax.swing.JDialog {

    /**
     * Creates new form front
     */
    int width = Toolkit.getDefaultToolkit().getScreenSize().width/3;
    int height = Toolkit.getDefaultToolkit().getScreenSize().height/10;
    File target_file = null;
    int dialog_value =1 ;
    public front(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        send_action.setVisible(false);
        recieve_action.setVisible(false);
        connection.setVisible(true);
        sr_button.setVisible(false);
        this.setLocation(width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sr_button = new javax.swing.JPanel();
        send = new javax.swing.JButton();
        recieve = new javax.swing.JButton();
        recieve_action = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        send_action = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        connection = new javax.swing.JPanel();
        wifi_host = new javax.swing.JButton();
        wifi_connect = new javax.swing.JButton();
        cross = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sr_button.setBackground(new java.awt.Color(0, 0, 0));

        send.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        send.setText("SEND");
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });
        sr_button.add(send);

        recieve.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        recieve.setText("RECIEVE");
        recieve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recieveMouseClicked(evt);
            }
        });
        sr_button.add(recieve);

        getContentPane().add(sr_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 180, 110));

        recieve_action.setBackground(new java.awt.Color(204, 204, 204));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setText("receving");
        recieve_action.add(jTextField1);

        getContentPane().add(recieve_action, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 270, 140));

        send_action.setBackground(new java.awt.Color(204, 204, 204));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField2.setText("sending");
        send_action.add(jTextField2);

        getContentPane().add(send_action, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 270, 140));

        connection.setBackground(new java.awt.Color(204, 204, 204));

        wifi_host.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        wifi_host.setText("HOST");
        wifi_host.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wifi_hostMouseClicked(evt);
            }
        });
        connection.add(wifi_host);

        wifi_connect.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        wifi_connect.setText("CONNECT");
        wifi_connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wifi_connectMouseClicked(evt);
            }
        });
        connection.add(wifi_connect);

        getContentPane().add(connection, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 270, 140));

        cross.setText(" ");
        cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossMouseClicked(evt);
            }
        });
        getContentPane().add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 20));

        menu.setText(" ");
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 20));

        status.setBackground(new java.awt.Color(204, 204, 255));
        status.setText(" 0%");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRONTll.png"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseClicked
        try {
            Process processs  = Runtime.getRuntime().exec("cmd /c netsh wlan stop hosted network");
        } catch (IOException ex) {
            Logger.getLogger(front.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_crossMouseClicked
    void print(){
        
        System.out.print("uutut");
    }
    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        sr_button.setVisible(false);
        print();
        send_action.setVisible(true);
        client c = new client();
        try {
            int i=0;
        while(i>300000000){
            i++;
        }
            c.send(status);
            
        } catch (Exception ex) {
            Logger.getLogger(front.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        sr_button.setVisible(true);
        send_action.setVisible(false);
    }//GEN-LAST:event_sendMouseClicked

    private void recieveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recieveMouseClicked
       sr_button.setVisible(false);print();
           recieve_action.setVisible(true);
       try { 
        System.out.print("**");
        int i=0;
        while(i>30000){
            i++;
        }
        } catch (Exception ex) {
            Logger.getLogger(front.class.getName()).log(Level.SEVERE, null, ex);
        }
        server ser = new server();
        //ser.serve(status);
        recieve_action.setVisible(false);
        sr_button.setVisible(true);

    }//GEN-LAST:event_recieveMouseClicked

    private void wifi_connectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wifi_connectMouseClicked
       JOptionPane.showMessageDialog(null, "connect to wifi network name \"YourSSID\" on other pc");
        connection.setVisible(false);
        sr_button.setVisible(true);
    }//GEN-LAST:event_wifi_connectMouseClicked

    private void wifi_hostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wifi_hostMouseClicked
        try {
            JOptionPane.showMessageDialog(null, "connect to wifi name yourssid on other pc");
            Process p = Runtime.getRuntime().exec("cmd /c netsh wlan disconnect");
            Process process  = Runtime.getRuntime().exec("cmd /c netsh wlan set hostednetwork mode=allow ssid=YourSSID key=12548446 keyusage=persistent");
            Process processs  = Runtime.getRuntime().exec("cmd /c netsh wlan start hosted network");
            
            connection.setVisible(false);
            sr_button.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(front.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_wifi_hostMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                front dialog = new front(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel connection;
    private javax.swing.JLabel cross;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel menu;
    private javax.swing.JButton recieve;
    private javax.swing.JPanel recieve_action;
    private javax.swing.JButton send;
    private javax.swing.JPanel send_action;
    private javax.swing.JPanel sr_button;
    private javax.swing.JTextField status;
    private javax.swing.JButton wifi_connect;
    private javax.swing.JButton wifi_host;
    // End of variables declaration//GEN-END:variables
}
